### ISSUE TITLE
Remove the version numbers when specifying the flags in stack.yaml

### ISSUE THREAD

**Issue by capitanbatata** [TorXakis/TorXakis#553]
In the newest version of stack (`1.6.1`) [it is possible](https://github.com/commercialhaskell/stack/issues/3583) to specify a flag for a snapshot package. So that means that we can go from 

```yaml
extra-deps:
- text-1.2.2.2

# ...

flags: 
  text: 
    integer-simple: true
```

To simply:
```yaml
flags: 
  text: 
    integer-simple: true
```

Our `stack.yaml` and `stack_linux.yaml` should be upgraded accordingly.
