### ISSUE TITLE
stack lock files

### ISSUE THREAD

**Issue by pjljvandelaar** [TorXakis/TorXakis#909]
Should we put the stack lock files under version control?
Or should we make TorXakis such that lock files are not needed: higher quality of dependencies...

For more info see: https://docs.haskellstack.org/en/stable/lock_files/

Our lock file currently contains
```
# This file was autogenerated by Stack.
# You should not edit this file by hand.
# For more information, please see the documentation at:
#   https://docs.haskellstack.org/en/stable/lock_files

packages:
- completed:
    cabal-file:
      size: 2957
      sha256: 86721de77129c198aa3f033c79c0f7aaebce16615e6e4ea73cefb3d9771e5a94
    name: text-via-sockets
    version: 0.1.0.0
    git: https://github.com/TorXakis/text-via-sockets.git
    pantry-tree:
      size: 682
      sha256: 5e30ecba223e12674b7b37e668af407bbdebeea117fd3a60306a42dd636056c0
    commit: e3228cd0407ec0d7991a544e154ea2def184fcae
  original:
    git: https://github.com/TorXakis/text-via-sockets.git
    commit: e3228cd0407ec0d7991a544e154ea2def184fcae
snapshots:
- completed:
    size: 527836
    url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/11/22.yaml
    sha256: 341870ac98d8a9f8f77c4adf2e9e0b22063e264a7fbeb4c85b7af5f380dac60e
  original: lts-11.22
```
